spring:
  datasource:
#  数据源基本配置
     username: root
     password: 960626
     url: jdbc:mysql://39.96.0.70:3306/zx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
     driver-class-name: com.mysql.cj.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource

     druid:
#    数据源其他配置
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        time-between-eviction-runs-millis:  60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
#    配置监控统计拦截的filters,去掉后监控界面sql无法统计，‘wall’用于防火墙
        filters:  stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        connection-properties:  druid.stat.mergeSql=true;durid.stat.slowSqlMillis=500
       #配置DruidStatFilter
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions:  .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*

    #配置DruidstatViewServlet
        stat-view-servlet:
           url-pattern: /druid/*

        # IP 白名单，没有配置或者为空，则允许所有访问
           allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
#        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
           reset-enable: false
        # 登录用户名/密码
           login-username: admin
           login-password: 960626


#设置xml文件生成的路径
mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.zx.decoration
    configuration.cache-enabled: false
    configuration.jdbc-type-for-null: null

